apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: zenko-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - zenko-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - zenko.io
  resources:
  - '*'
  - zenkos
  - zenkoconfigurationoverlays
  - zenkoversions
  verbs:
  - '*'
- apiGroups:
  - kubedb.com
  resources:
  - mongodbs
  - redises
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - zookeeperclusters
  verbs:
  - '*'
- apiGroups:
  - kafka.banzaicloud.io
  resources:
  - kafkaclusters
  verbs:
  - '*'
